### ISSUE TITLE
Support  youtu.be urls

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSYouTube#19]
Example:
>  http://youtu.be/81wkbBqb6TY 

From: https://www.alledia.com/forum/osyoutube/71/#336

**Comment by htmgarcia** [comment]
Maybe as pro feature?

**Comment by stevejburge** [comment]
Good point, yes we should do this

**Comment by htmgarcia** [comment]
Issue created in pro repository https://github.com/OSTraining/OSYouTube-Pro/issues/20
