### ISSUE TITLE
Ignore HTML links not working

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSYouTube#20]
The links are still being converted into embeds.
Examples:
```
<p><a href="https://www.youtube.com/watch?v=jEiGbXvF_Rw">https://www.youtube.com/watch?v=jEiGbXvF_Rw</a></p>
<p><a href="https://www.youtube.com/watch?v=jEiGbXvF_Rw">Linked video</a></p>
```

Related to https://www.alledia.com/forum/osyoutube/94/#556

**Comment by htmgarcia** [comment]
@billtomczak with "Ignore HTML links" as yes, [the new commit](https://github.com/OSTraining/OSYouTube/commit/253dc522927785031d7204d586c1a7b66b28ccc3) and [this code](https://github.com/OSTraining/OSYouTube/issues/20#issue-63763591)
![osy](https://cloud.githubusercontent.com/assets/4999794/11983871/96e08ef6-a97c-11e5-9849-ce7a5ecd2075.jpg)

**Comment by OSTraining** [comment]
Can you provide the code that caused this?

**Comment by htmgarcia** [comment]
Sure thing:
```<p><a href="https://www.youtube.com/watch?v=jEiGbXvF_Rw">https://www.youtube.com/watch?v=jEiGbXvF_Rw</a></p>
<p><a href="https://www.youtube.com/watch?v=jEiGbXvF_Rw">Linked video</a></p>```

**Comment by billtomczak** [comment]
Sorry - I missed your link in the previous comment :)

**Comment by OSTraining** [comment]
Can you try again? Maybe a caching issue? It works for me

**Comment by OSTraining** [comment]
I'm getting a completely different result with that snippet.

with `ignoreHTML = Yes` I get no embedding at all. set to `No` I get the embed doubled up.

**Comment by htmgarcia** [comment]
lol - I forgot to disable OSEmbed in the same installation :D
@billtomczak sorry for the troubles. It works!

**Comment by billtomczak** [comment]
np! Glad everything worked out! Okay to close this?

**Comment by htmgarcia** [comment]
Yes. Thanks!
