### ISSUE TITLE
Embed overlay dropdown menu

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSYouTube#23]
From: https://secure.helpscout.net/conversation/94666017/12777/

**Comment by htmgarcia** [comment]
@andergmartins I'm not sure if this is the right place: https://github.com/OSTraining/OSYouTube/commit/251a28bc22d79cd4e90fe04ff09f3d0f4a72af45

I appreciate your thoughts.

**Comment by andergmartins** [comment]
@htmgarcia, Yes, that is fine :) Good job

**Comment by htmgarcia** [comment]
Fix https://github.com/OSTraining/OSYouTube/commit/b5b1b83485c4595814be6078a4d1bc26e4e0bd99
