### ISSUE TITLE
FF in Mac hide video controls if the site is in http

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSYouTube#26]
We are injecting the embed url using a relative protocol: `//www....`. YouTube player seems to have an issue with the video being loaded in http mode. Easy to fix forcing to https always.

**Comment by htmgarcia** [comment]
Finally, I was able to reproduce the issue in a personal site. 
Firefox 43.0.4

**Comment by htmgarcia** [comment]
I implemented the [fix](https://github.com/OSTraining/OSYouTube/commit/762947bcc979f9aecf5810b54a1f5201be635913) with no luck. 

The embed is broken in my test.

```
<iframe width="425" height="344" frameborder="0" src="/<iframe width="480" height="270" src="https://www.youtube.com/embed/A_0NEVzXekU?feature=oembed" frameborder="0" allowfullscreen></iframe>" allowfullscreen></iframe>
```

**Comment by andergmartins** [comment]
Odd thing. Do you have OSEmbed installed there too?

**Comment by htmgarcia** [comment]
Now I think, I have it - lol
Still would be a conflict, I think.

**Comment by andergmartins** [comment]
:) Ok. What about if OSEmbed would be able to detect if OSYouTube is installed, and in positive case just skip YouTube URLs and keep that for OSYouTube? (do the same for Vimeo or Wistia)

**Comment by htmgarcia** [comment]
+1
